services:
  - type: web
    name: pubg-pop-bot
    runtime: python
    envVars:
      TOKEN:
        fromDatabase: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
